
# Alacritty configuration (alacritty.toml)
import = ["./dracula.toml"]

# Font configuration
[font]
normal.family = "FiraCode Nerd Font" # or "Hack", "JetBrains Mono", "Fira Code", etc.
normal.style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

# size = 11.0

# Offset is the extra space around each character.
[font.offset]
x = 0
y = 0

# Glyph offset determines the locations of the glyphs within their cells
[font.glyph_offset]
x = 0
y = 0

# Use built-in font for box drawing characters.
# use_builtin_box_drawing = true

# Window configuration
[window]
# Window dimensions (changes require restart)
# [window.dimensions]
# columns = 0 # 0 sets default
# lines = 0   # 0 sets default

# Window padding (changes require restart)
[window.padding]
x = 10
y = 10

[window]
Decorations = false 
# Decorations

# Allow dead keys to compose special characters.
# Requires `Option Compose` to be set in your desktop environment.
# allow_dead_keys = true

# Scrolling configuration
[scrolling]
# Maximum number of lines in the scrollback buffer.
history = 10000

# Number of lines the viewport will move for every line scrolled when scrollback is enabled.
multiplier = 3

# Cursor configuration
[cursor]
# Cursor style
style = "Beam" # or "Block", "Underline"

[terminal]

# Shell
[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
