
# Alacritty configuration (alacritty.toml)

# Colors (Nord)
[colors]
# Default colors
primary.background = "#2e3440"
primary.foreground = "#d8dee9"

# Normal colors
[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

# Bright colors
[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

# Cursor colors
[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

# Selection colors
[colors.selection]
text = "#2e3440"
background = "#a0a7b4"

# Search colors
[colors.search.matches]
foreground = "#2e3440"
background = "#88c0d0"

[colors.search.focused_match]
foreground = "#2e3440"
background = "#bf616a"

# Hints colors
[colors.hints.start]
foreground = "#2e3440"
background = "#ebcb8b"

[colors.hints.end]
foreground = "#ebcb8b"
background = "#2e3440"

# Font configuration
[font]
normal.family = "monospace" # or "Hack", "JetBrains Mono", "Fira Code", etc.
normal.style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

# size = 11.0

# Offset is the extra space around each character.
[font.offset]
x = 0
y = 0

# Glyph offset determines the locations of the glyphs within their cells
[font.glyph_offset]
x = 0
y = 0

# Use built-in font for box drawing characters.
# use_builtin_box_drawing = true

# Window configuration
[window]
# Window dimensions (changes require restart)
# [window.dimensions]
# columns = 0 # 0 sets default
# lines = 0   # 0 sets default

# Window padding (changes require restart)
[window.padding]
x = 10
y = 10

# Decorations

# Allow dead keys to compose special characters.
# Requires `Option Compose` to be set in your desktop environment.
# allow_dead_keys = true

# Scrolling configuration
[scrolling]
# Maximum number of lines in the scrollback buffer.
history = 10000

# Number of lines the viewport will move for every line scrolled when scrollback is enabled.
multiplier = 3

# Cursor configuration
[cursor]
# Cursor style
style = "Beam" # or "Block", "Underline"

[terminal]

# Shell
[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
